title: Luis Justin
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Luis Justin
  email: luisjustin@protonmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "deploy.sh", "server.sh"]

prose:
  rooturl: '_posts'
  siteurl: 'http://luisjustin.com.br/'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Titulo"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Data Da Postagem"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "multiselect"
          label: "Adicionar Categorias"
          placeholder: "Choose Tags"
          options:
            - name: "Laravel"
              value: "Laravel"
            - name: "Flask"
              value: "Flask"
            - name: "FastAPI"
              value: "FastAPI"
            - name: "PHP"
              value: "PHP"
            - name: "Python"
              value: "Python"
            - name: "Java"
              value: "Java"
            - name: "Shell Script"
              value: "Shell Script"
            - name: "Linux"
              value: "Linux"
            - name: "Ubuntu"
              value: "Ubuntu"

