title: Luis Justin
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Luis Justin
  email: luisjustin@protonmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

#collections_dir: all_collections
#collections:
#  posts:
#    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:year/:month/:day/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

prose:
    rooturl: "_posts"
    siteurl: "https://luisjustin.com.br"
    media: "assets/images"
    metadata:
        _posts:
          - name: "title"
              field:
                element: "text"
                label: "Titulo"
          - name: "layout"
              field:
                element: "hidden"
                value: "post"
          - name: "categories"
              field:
                element: "multiselect"
                label: "Adicionar Categorias"
                options:
                  - name: "Laravel"
                    value: "Laravel"
                  - name: "PHP"
                    value: "PHP"
                  - name: "Python"
                    value: "Python"
                  - name: "NGINX"
                    value: "NGINX"
          - name: "date":
              field:
                element: "hidden"
                value: CURRENT_DATETIME
