title: Luis Justin
markdown: kramdown
url: "https://luisjustin.com.br"
baseurl: ""

twitter:
  username: HelloWar75
  card: summary

social:
  name: Luis Henrique Justin
  links:
    - https://www.linkedin.com/in/luisjustin/
    - https://github.com/HelloWar75
    - https://twitter.com/HelloWar75
    - https://dev.to/hellowar75

# for atom feed
author:
  name: Luis Justin
  email: luisjustin@protonmail.com
  twitter: HelloWar75

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:year/:month/:day/:title/
      image: "https://s.gravatar.com/avatar/e655417468fe9d965cddf68455f557d9?s=460"

exclude: ["LICENSE", "README.md", "deploy.sh", "server.sh"]

prose:
  rooturl: '_posts'
  siteurl: 'https://luisjustin.com.br/'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Titulo"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Data Da Postagem"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "multiselect"
          label: "Adicionar Categorias"
          placeholder: "Choose Tags"
          options:
            - name: "Laravel"
              value: "Laravel"
            - name: "Flask"
              value: "Flask"
            - name: "FastAPI"
              value: "FastAPI"
            - name: "PHP"
              value: "PHP"
            - name: "Python"
              value: "Python"
            - name: "Java"
              value: "Java"
            - name: "Shell Script"
              value: "Shell Script"
            - name: "Linux"
              value: "Linux"
            - name: "Ubuntu"
              value: "Ubuntu"

