title: Luis Justin
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Luis Justin
  email: luisjustin@protonmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:year/:month/:day/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

prose:
    metadata:
        - "all_collections/_posts":
            - name: "layout"
                field:
                    value: "post"
            