# This is a basic workflow to help you get started with Actions
# bundle exec jekyll build -d /var/www/luisjustin-com-br/

name: CI

on: [ push ]

jobs:
  deploy_site:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server updated site files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull
      - name: Run Jekyll build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: source ./exports_need.sh && cd ${{ secrets.PROJECT_PATH }} && bundle exec jekyll build -d ${{ secrets.JEKYLL_DEST_PATH }}
